#!/bin/bash

ABSOLUTE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
command="$1"
filename="$ABSOLUTE_PATH/myway.data"

if [ ! -e "$filename" ]; then
    echo -n "" >> "$filename"
	truncate -s 0 "$filename"
fi 

if [ "$command" == "go" ] ; then

	
	while read -r line
	do
	    data="$line"
	    name="${data%%=*}"
		path="${data##*=}"

		a="$name"
		b="$2"

		if [ "$a" == "$b" ]; then
	    	cd $path
		fi
	done < "$filename"
fi

if [ "$command" == "add" ] ; then
	newpath="$(pwd)"
	exists="0"
	while read -r line
	do
	    data="$line"
	    name="${data%%=*}"
		path="${data##*=}"

		if [ "$name" == "$2" ]; then
	    	echo "MyWay: this name is already exists."
			exists="1"
			break
		fi
		if [ "$path" == "$newpath" ]; then
	    	echo "MyWay: this path is already exists."
			exists="1"
			break
		fi

	done < "$filename"
	if [ "$exists" == "0" ] ; then
		echo "$2=$newpath" >> $filename
		echo "MyWay: repository added to list."
	fi
fi

if [ "$command" == "delete" ] ; then
	echo -n "" >> "mywaynew.data"
	truncate -s 0 "mywaynew.data"
	while read -r line
	do
	    data="$line"
	    name="${data%%=*}"
		path="${data##*=}"

		if [ "$name" == "$2" ]; then
	    	echo "MyWay: repository name deleted."
		else 
			echo "$line" >> "mywaynew.data"
		fi

	done < "$filename"
	mv "mywaynew.data" "$filename"
fi

if [ "$command" == "list" ] ; then
	cat $filename
fi

if [[ ("$command" == "help") || ("$command" == "") ]] ; then
	echo ""
	echo "MyWay: v1.0"
	echo "Vitaliy Grusha"
	echo "Access easily to your directories by a short name."
	echo ""
	echo "Commands:"
	echo ""
	echo "    myway add <shortname>"
	echo "        Attach current path to shortname."
	echo ""
	echo "    myway delete <shortname>"
	echo "        Delete shortname."
	echo ""
	echo "    myway list"
	echo "        Show list of all registred shortnames."
	echo ""
	echo "    myway go <shortname>"
	echo "        Change current directory on attached to shortname."
	echo ""
fi
